version: "3"
services:
  org-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: org1-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://my-agent-1:8000"
      ACAPY_LABEL: "Org Agent"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8001"
      AGENT_PORT: "8000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8001 \
        --admin-insecure-mode \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http \
        --wallet-type indy \
        --multitenant-admin \
        --jwt-secret secret123 \
        --wallet-name org1wallet \
        --wallet-key s123 \
        --genesis-url http://localhost:9000/genesis \
        --multitenant"

    ]
    ports:
      - "8001:8001"

  controller:
    build: 
      context:  ./controller
      dockerfile: docker/app.Dockerfile
    depends_on:
      - controller-db
    ports:
      - "8080:8080"



  controller-db:
    image: postgres:latest
    restart: always
    hostname: db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: controller_db
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
      # - ./.postgres:/var/lib/postgresql
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-init.d/create_tables.sql
    ports: 
      - "5432:5432"
  
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050

  ngrok-tails-server:
    image: wernight/ngrok
    networks:
      - tails-server
    ports:
      - 4044:4040
    command: ngrok http tails-server:6543 --log stdout

  tails-server:
    build:
      context: ../../repo/indy-tails-server/
      dockerfile: docker/Dockerfile.tails-server
      # dockerfile: ../repo/indy-tails-server/docker/Dockerfile.tails-server
    ports:
      - 6543:6543
    networks:
      - tails-server
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --log-level 0

networks:
  tails-server:
        
# --storage-path $STORAGE_PATH
  #  agent-2:
  #   image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
  #   container_name: my-agent-2
  #   environment:
  #     ACAPY_ADMIN_INSECURE_MODE: "true"
  #     ACAPY_AUTO_PROVISION: "true"
  #     ACAPY_DEBUG_CONNECTIONS: "true"
  #     ACAPY_ENDPOINT: "http://my-agent-2:9000"
  #     ACAPY_LABEL: "Agent 2"
  #     ACAPY_LOG_LEVEL: "info"
  #     ACAPY_NO_LEDGER: "true"
  #     ADMIN_PORT: "9001"
  #     AGENT_PORT: "9000"
  #   entrypoint: /bin/bash
  #   command: ["-c",
  #       "aca-py start \
  #       --admin '0.0.0.0' 9001 \
  #       --inbound-transport http '0.0.0.0' 9000 \
  #       --outbound-transport http "
  #   ]
  #   ports:
  #     - "9001:9001"
