version: "3"
services:
  org-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: org1-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://my-agent-1:8000"
      ACAPY_LABEL: "Org Agent"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8001"
      AGENT_PORT: "8000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' ${ADMIN_PORT} \
        --admin-insecure-mode \
        --inbound-transport http '0.0.0.0' ${AGENT_PORT} \
        --outbound-transport http \
        --wallet-type indy \
        --jwt-secret ${JWT_SECRET} \
        --wallet-name ${WALLET_NAME} \
        --wallet-key ${WALLET_KEY} \
        --multitenant-admin \
        --genesis-url ${GENESIS_URL} \
        --multitenant"

    ]
    ports:
      - "8001:8001"

  controller:
    build: 
      context:  ./controller
      dockerfile: docker/app.Dockerfile
    depends_on:
      - controller-db
    ports:
      - "8080:8080"



  controller-db:
    image: postgres:latest
    restart: always
    hostname: db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: controller_db
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
      # - ./.postgres:/var/lib/postgresql
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-init.d/create_tables.sql
    ports: 
      - "5432:5432"
  
  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050


# This should be configured when tails server is implemented
  # ngrok-tails-server:
  #   image: wernight/ngrok
  #   networks:
  #     - tails-server
  #   ports:
  #     - 4044:4040
  #   command: ngrok http tails-server:6543 --log stdout

#   tails-server:
#     build:
#       context: ../../repo/indy-tails-server/
#       dockerfile: docker/Dockerfile.tails-server
#       # dockerfile: ../repo/indy-tails-server/docker/Dockerfile.tails-server
#     ports:
#       - 6543:6543
#     networks:
#       - tails-server
#     command: >
#       tails-server
#         --host 0.0.0.0
#         --port 6543
#         --log-level 0

# networks:
#   tails-server:
